"""Ironsworn's moves, oracles and assets from Datasworn, as pack files.

Datasworn (github.com/rsek/datasworn) publishes Ironsworn's rules as JSON, and each object
says what license it is under (`_source.license`, else the license of what holds it). The
moves, oracles and assets are CC BY 4.0, which lets this project ship them with credit; the
rest of the book (NPCs, the atlas, the truths) is CC BY-NC-SA, and is left out and counted.
The engine reads what this writes: moves/<id>.toml, tables/<id>.toml, assets/<id>.toml.

Every file carries where it came from and says not to edit it: a fix goes in this file, and
the import runs again. A file in those folders that doesn't carry the header is somebody's
own and is never touched.
"""

import re
from pathlib import Path

from . import SoloError, packs

CC_BY = "https://creativecommons.org/licenses/by/4.0"
HEADER = "# Generated by `solo import datasworn` from {title} by {authors}, Datasworn {version}: CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/)."
# The tables a GM asks for by a short name; every other one is its path in the book, joined by _.
SHORT = {
    "action_and_theme/action": "action", "action_and_theme/theme": "theme", "moves/pay_the_price": "pay_the_price",
    "moves/endure_harm": "endure_harm", "moves/endure_stress": "endure_stress", "turning_point/combat_action": "combat_action",
    "turning_point/mystic_backlash": "mystic_backlash", "turning_point/major_plot_twist": "major_plot_twist",
    "turning_point/challenge_rank": "challenge_rank",
}
# The yes/no oracle is the engine's ([oracle] odds in system.toml): these tables only give its numbers.
ASK = "moves/ask_the_oracle/"
_KINDS = {"action_roll": "action", "progress_roll": "progress", "special_track": "progress", "no_roll": "none"}
_TRACKS = {"Vow": "vow", "Journey": "journey", "Combat": "combat"}
_LEFT_OUT = ("atlas", "npcs", "truths", "rarities", "delve_sites", "site_domains", "site_themes")


def build(data, out):
    """Write the pack files for what Datasworn's ruleset `data` holds under CC BY. Returns what was
    done: counts, what was left out, the odds the ask-the-oracle tables give, and things to look at."""
    if data.get("type") != "ruleset" or not str(data.get("datasworn_version", "")).startswith("0.0."):
        raise SoloError(f"this reads a Datasworn 0.0 ruleset (Ironsworn classic); this is a {data.get('type')} at version {data.get('datasworn_version')}")
    package = data.get("license", "")
    header = HEADER.format(title=data["title"], authors=", ".join(a["name"] for a in data["authors"]), version=data["datasworn_version"])
    tables = _tables(data["oracles"], package)
    asked = {key: node for key, node, _, _ in tables if key.startswith(ASK)}
    ids = {key: SHORT.get(key) or key.replace("/", "_") for key, _, group, taken in tables if taken and key not in asked}
    notes = []
    book = [(collection, move_id, move) for collection in data["moves"].values() for move_id, move in collection["contents"].items()]
    files = {
        "tables": {ids[key]: _table(node, group, key, ids, header, notes) for key, node, group, taken in tables if key in ids},
        "moves": {move_id: _move(move, collection["name"], number, ids, header, notes)
                  for number, (collection, move_id, move) in enumerate(book)
                  if _cc_by(_license(move, _license(collection, package)))},
        "assets": {asset_id: _asset(asset, collection["name"], header)
                   for collection in data["assets"].values() for asset_id, asset in collection["contents"].items()
                   if _cc_by(_license(asset, _license(collection, package)))},
    }
    for folder, written in files.items():
        _write(Path(out) / folder, written)
    return {"moves": len(files["moves"]), "tables": len(files["tables"]), "assets": len(files["assets"]),
            "left_out": _left_out(data, package, tables), "odds": _odds(asked), "notes": notes}


def _license(node, inherited):
    return (node.get("_source") or {}).get("license") or inherited


def _cc_by(license):
    return license.rstrip("/").replace("http://", "https://") == CC_BY


def _tables(oracles, package):
    """[(path, table, the collection's name if it isn't a top one, under CC BY)] for every table
    in the oracles, however deep the collections holding it go."""
    found = []

    def walk(collections, path, inherited):
        for kind in ("contents", "collections"):
            for name, node in (collections.get(kind) or {}).items():
                here, license = f"{path}/{name}" if path else name, _license(node, inherited)
                if "rows" in node:
                    found.append((here, node, collections.get("name") if path.count("/") else None, _cc_by(license)))
                else:
                    walk(node, here, license)
    walk({"collections": oracles}, "", package)
    return found


def _left_out(data, package, tables):
    """What isn't imported, and under which license: whole kinds of content, and tables not under CC BY."""
    gone = {}
    for kind in _LEFT_OUT:
        if data.get(kind):
            licenses = {_license(entry, package).rsplit("licenses/", 1)[-1] for entry in data[kind].values()}
            gone[kind] = f"{len(data[kind])} ({', '.join(sorted(licenses))})"
    other = [key for key, _, _, taken in tables if not taken]
    if other:
        gone["tables"] = f"{len(other)} not under CC BY: {', '.join(other)}"
    return gone


def _odds(asked):
    """The chance of a yes at each odds, from the rows of the ask-the-oracle tables that say Yes."""
    return {node["name"].lower(): sum(r["max"] - r["min"] + 1 for r in node["rows"] if r["text"].strip().lower() == "yes") for node in asked.values()}


def _table(node, group, key, ids, header, notes):
    """A table's file. A row that sends you on to another table (or to roll twice on this one)
    says so as `then`, which the engine follows."""
    name = f"{group}: {node['name']}" if group else node["name"]
    formula = "1" + node["dice"] if node["dice"].startswith("d") else node["dice"]
    lines = [header, f"name = {packs.toml_string(name)}", f"formula = {packs.toml_string(formula)}", f"source = {packs.toml_string(_source(node))}", "results = ["]
    for row in node["rows"]:
        then = []
        for roll in row.get("oracle_rolls") or []:
            target = ids.get(roll["oracle"].removeprefix("classic/oracles/")) if roll.get("oracle") else ids[key]
            if target:
                then += [target] * int(roll.get("number_of_rolls") or 1)
            else:
                notes.append(f"table {ids[key]}, {row['min']}-{row['max']}: sends you to {roll['oracle']}, which isn't imported")
        follow = f", then = {_value(then)}" if then else ""
        lines.append(f"  {{ range = [{row['min']}, {row['max']}], text = {packs.toml_string(_clean(row['text'], ids))}{follow} }},")
    return "\n".join([*lines, "]"]) + "\n"


def _move(move, category, number, ids, header, notes):
    """A move's file: what it rolls, and the words it and its results are given in. `order` is
    where the book puts it, so a list of moves reads in the book's order."""
    kind, stats, methods = _KINDS[move["roll_type"]], [], set()
    for condition in (move.get("trigger") or {}).get("conditions") or []:
        for option in condition.get("roll_options") or []:
            if option["using"] not in ("stat", "condition_meter", "progress_track", "bonds_track"):
                # It rolls something the sheet doesn't hold (a companion's health, on its asset card): the words are all there is.
                notes.append(f"move {move['_id'].rsplit('/', 1)[-1]} rolls something the engine doesn't keep ({option['using']}), so it has no roll: read it")
                kind = "none"
            name = option.get("stat") or option.get("condition_meter")
            if name and name not in stats:
                stats.append(name)
        if condition.get("roll_options"):
            methods.add(condition["method"])
    fields = [("name", move["name"]), ("category", category), ("order", number), ("kind", kind)]
    if kind == "action":
        fields.append(("stats", stats))
        fields += [("pick", next(iter(methods)))] if len(methods) == 1 and methods <= {"highest", "lowest"} else []
    elif kind == "progress":
        fields.append(("track", _TRACKS.get((move.get("tracks") or {}).get("category"), "bonds")))
    tables = [ids[t] for t in (o.removeprefix("classic/oracles/") for o in move.get("oracles") or []) if t in ids]
    fields += [("oracle", tables)] if tables else []
    fields.append(("source", _source(move)))
    lines = [header, *[f"{key} = {_value(value)}" for key, value in fields], f"text = {_string(_clean(move['text'], ids))}"]
    if kind != "none":
        lines += ["", "[outcomes]", *[f"{hit} = {_string(_clean(move['outcomes'][hit]['text'], ids))}" for hit in ("strong_hit", "weak_hit", "miss")]]
    return "\n".join(lines) + "\n"


def _asset(asset, category, header):
    """An asset's file: its abilities, of which the ones marked `enabled` are the ones a new hero has."""
    health = ((asset.get("controls") or {}).get("health") or {}).get("max")
    fields = [("name", asset["name"]), ("category", asset.get("category") or category)]
    fields += [("requirement", _clean(asset["requirement"], {}))] if asset.get("requirement") else []
    lines = [header, *[f"{key} = {_value(value)}" for key, value in fields], *([f"health = {health}"] if health else []),
             f"source = {packs.toml_string(_source(asset))}", "abilities = ["]
    for ability in asset["abilities"]:
        named = f"name = {packs.toml_string(ability['name'])}, " if ability.get("name") else ""
        lines.append(f"  {{ {named}text = {packs.toml_string(_clean(ability['text'], {}))}, enabled = {'true' if ability['enabled'] else 'false'} }},")
    return "\n".join([*lines, "]"]) + "\n"


def _source(item):
    """Where in the book: "Ironsworn Rulebook, p. 60"."""
    source = item.get("_source") or {}
    return source.get("title", "Ironsworn Rulebook") + (f", p. {source['page']}" if source.get("page") else "")


def _clean(text, ids):
    """Datasworn's Markdown as this project's: a link to another part of the book becomes its words,
    __bold__ is **bold**, and a {{table:...}} says which table to roll."""
    def table(found):
        table_id = ids.get(found.group(1).removeprefix("classic/oracles/"))
        return f"(roll it with solo table {table_id})" if table_id else ""

    text = re.sub(r"\[([^\]]+)\]\(id:[^)]*\)", r"\1", text)
    text = re.sub(r"__([^_]+)__", r"**\1**", text)
    return re.sub(r"\{\{table:([^}]*)\}\}", table, text).strip()


def _value(value):
    if isinstance(value, list):
        return f"[{', '.join(packs.toml_string(v) for v in value)}]"
    elif isinstance(value, int):
        return str(value)
    else:
        return packs.toml_string(value)


def _string(text):
    """A TOML string that reads like the text: a multi-line one where it has lines."""
    if "\n" not in text:
        return packs.toml_string(text)
    else:
        escaped = text.replace("\\", "\\\\").replace('"""', '""\\"')
        # A multi-line string can't hold a control character other than a tab or a line break.
        escaped = re.sub(r"[\x00-\x08\x0b-\x1f\x7f]", lambda found: f"\\u{ord(found.group()):04x}", escaped)
        # The value is the text exactly: it ends where the closing quotes begin, and a quote of its own is escaped.
        escaped = escaped[:-1] + '\\"' if escaped.endswith('"') else escaped
        return '"""\n' + escaped + '"""'


def _write(folder, files):
    """The files, each named for its id. A generated file no longer wanted goes; one without the header stays."""
    folder.mkdir(parents=True, exist_ok=True)
    for path in folder.glob("*.toml"):
        if path.stem not in files and _generated(path):
            path.unlink()
    for file_id, text in files.items():
        path = folder / f"{file_id}.toml"
        if not path.exists() or _generated(path):
            path.write_text(text, encoding="utf-8")


def _generated(path):
    return path.read_text(encoding="utf-8").startswith("# Generated by `solo import datasworn`")
